package edu.pitt.cs;

// Generated by Selenium IDE
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import java.time.Duration;
import org.openqa.selenium.chrome.ChromeOptions;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public void TestFixture() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
  }
  @Test
  public void testFixture() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
  }
  @Test
  public void tEST1LINKS() {
    TestFixture();
    {
      WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'Reset\')]"));
      String attribute = element.getAttribute("href");
      vars.put("resetHref", attribute);
    }
    assertEquals(vars.get("resetHref").toString(), "http://localhost:8080/reset");
  }
  @Test
  public void tEST2RESET() {
    TestFixture();
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    driver.findElement(By.linkText("Reset")).click();
    assertThat(driver.findElement(By.xpath("//li[@id=\'cat-id1\']")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.xpath("//li[@id=\'cat-id2\']")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//li[@id=\'cat-id3\']")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST3CATALOG() {
    TestFixture();
    driver.findElement(By.linkText("Catalog")).click();
    {
      WebElement element = driver.findElement(By.xpath("//li[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("imgName", attribute);
    }
    assertEquals(vars.get("imgName").toString(), "http://localhost:8080/images/cat2.jpg");
  }
  @Test
  public void tEST4LISTING() {
    TestFixture();
    driver.findElement(By.xpath("//a[contains(text(),\'Catalog\')]")).click();
    vars.put("catCount", driver.findElements(By.xpath("//div[@id=\'listing\']/ul/li")).size());
    vars.put("catName", driver.findElement(By.xpath("//li[@id=\'cat-id3\']")).getText());
    assertEquals(vars.get("catCount").toString(), "3");
    assertEquals(vars.get("catName").toString(), "ID 3. Mistoffelees");
  }
  @Test
  public void tEST5RENTACAT() {
    TestFixture();
    driver.findElement(By.xpath("//a[contains(text(),\'Rent-A-Cat\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Rent\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Return\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST6RENT() {
    TestFixture();
    driver.findElement(By.xpath("//a[contains(text(),\'Rent-A-Cat\')]")).click();
    driver.findElement(By.xpath("//input[@id=\'rentID\']")).click();
    driver.findElement(By.xpath("//input[@id=\'rentID\']")).sendKeys("1");
    driver.findElement(By.xpath("//button[contains(.,\'Rent\')]")).click();
    vars.put("catName1", driver.findElement(By.xpath("//li[@id=\'cat-id1\']")).getText());
    vars.put("catName2", driver.findElement(By.xpath("//li[@id=\'cat-id2\']")).getText());
    vars.put("catName3", driver.findElement(By.xpath("//li[@id=\'cat-id3\']")).getText());
    vars.put("result", driver.findElement(By.xpath("//div[@id=\'rentResult\']")).getText());
    assertEquals(vars.get("catName1").toString(), "Rented out");
    assertEquals(vars.get("catName2").toString(), "ID 2. Old Deuteronomy");
    assertEquals(vars.get("catName3").toString(), "ID 3. Mistoffelees");
    assertEquals(vars.get("result").toString(), "Success!");
  }
  @Test
  public void tEST7RETURN() {
    TestFixture();
    js.executeScript("document.cookie = \"2=true\";");
    driver.findElement(By.xpath("//a[contains(text(),\'Rent-A-Cat\')]")).click();
    driver.findElement(By.xpath("//input[@id=\'returnID\']")).click();
    driver.findElement(By.xpath("//input[@id=\'returnID\']")).sendKeys("2");
    driver.findElement(By.xpath("//button[contains(.,\'Return\')]")).click();
    vars.put("catName1", driver.findElement(By.xpath("//li[@id=\'cat-id1\']")).getText());
    vars.put("catName2", driver.findElement(By.xpath("//li[@id=\'cat-id2\']")).getText());
    vars.put("catName3", driver.findElement(By.xpath("//li[@id=\'cat-id3\']")).getText());
    vars.put("result", driver.findElement(By.xpath("//div[@id=\'returnResult\']")).getText());
    assertEquals(vars.get("catName1").toString(), "ID 1. Jennyanydots");
    assertEquals(vars.get("catName2").toString(), "ID 2. Old Deuteronomy");
    assertEquals(vars.get("catName3").toString(), "ID 3. Mistoffelees");
    assertEquals(vars.get("result").toString(), "Success!");
  }
  @Test
  public void tEST8FEEDACAT() {
    TestFixture();
    driver.findElement(By.xpath("//a[contains(text(),\'Feed-A-Cat\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Feed\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST9FEED() {
    TestFixture();
    driver.findElement(By.xpath("//a[contains(text(),\'Feed-A-Cat\')]")).click();
    driver.findElement(By.xpath("//input[@id=\'catnips\']")).click();
    driver.findElement(By.id("catnips")).sendKeys("6");
    driver.findElement(By.xpath("//button[contains(.,\'Feed\')]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']")));
    }
    vars.put("result", driver.findElement(By.xpath("//div[@id=\'feedResult\']")).getText());
    assertEquals(vars.get("result").toString(), "Nom, nom, nom.");
  }
  @Test
  public void tEST10GREETACAT() {
    TestFixture();
    driver.findElement(By.xpath("//a[contains(text(),\'Greet-A-Cat\')]")).click();
    vars.put("meowText", driver.findElement(By.xpath("//div[@id=\'greeting\']/h4")).getText());
    assertEquals(vars.get("meowText").toString(), "Meow!Meow!Meow!");
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    TestFixture();
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    vars.put("meowText", driver.findElement(By.xpath("//div[@id=\'greeting\']/h4")).getText());
    assertEquals(vars.get("meowText").toString(), "Meow! from Jennyanydots.");
  }
}
